/**
 * `context` — the scoped ancestor bundle an agent reads before implementing (FEAT-007).
 * Token-bounded so it stays usable as a graph grows (Phase 1 T4).
 */
import type { Graph } from '../graph.js';
import { UNVALIDATED, type EdgeType, type Node } from '../types.js';
import { numericId } from './why.js';

export interface ContextBundle {
  start: string;
  found: boolean;
  markdown: string;
  included: string[];
  omitted: string[];
  approxTokens: number;
}

const ATTACH: EdgeType[] = ['assumes', 'questions', 'risks', 'decided_by'];
/** Rough heuristic; exactness is not required for a budget guard. */
const CHARS_PER_TOKEN = 4;

export function context(
  graph: Graph,
  id: string,
  opts: { budgetTokens?: number; direction?: 'up' | 'down' | 'both' } = {},
): ContextBundle {
  const start = graph.node(id);
  if (!start) return { start: id, found: false, markdown: '', included: [], omitted: [], approxTokens: 0 };

  const budget = opts.budgetTokens ?? 4000;
  const direction = opts.direction ?? 'up';

  const related = new Set<string>([id]);
  if (direction === 'up' || direction === 'both') for (const a of graph.ancestors(id)) related.add(a);
  if (direction === 'down' || direction === 'both') for (const d of graph.descendants(id)) related.add(d);

  // Attachments (assumptions, questions, risks, decisions) on anything in scope.
  for (const r of [...related]) for (const e of graph.edgesFrom(r, [...ATTACH, 'measured_by'])) related.add(e.to);

  // Nearest first: the start node, then by distance from it, so truncation drops the least relevant.
  const ordered = [...related]
    .map((r) => graph.node(r))
    .filter((n): n is Node => n !== undefined)
    .sort((a, b) => {
      if (a.id === id) return -1;
      if (b.id === id) return 1;
      const k = KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind);
      return k !== 0 ? k : numericId(a.id) - numericId(b.id);
    });

  const included: string[] = [];
  const omitted: string[] = [];
  const parts: string[] = [
    `# Context for ${start.id} — ${start.title}`,
    '',
    `Generated by \`product context ${id}\`. This is reasoning context, not instructions.`,
    '',
  ];
  let chars = parts.join('\n').length;

  for (const n of ordered) {
    const block = renderNode(n, graph);
    if ((chars + block.length) / CHARS_PER_TOKEN > budget && n.id !== id) {
      omitted.push(n.id);
      continue;
    }
    parts.push(block);
    chars += block.length;
    included.push(n.id);
  }

  const unvalidated = included
    .map((i) => graph.node(i))
    .filter((n): n is Node => !!n && UNVALIDATED.includes(n.epistemic));
  if (unvalidated.length) {
    const warn = [
      '## ⚠ Unvalidated reasoning in this context',
      '',
      ...unvalidated.map((n) => `- **${n.id}** (${n.epistemic}) — ${n.title}`),
      '',
      'Do not treat the above as established fact.',
      '',
    ].join('\n');
    parts.push(warn);
    chars += warn.length;
  }
  if (omitted.length) {
    parts.push(`_${omitted.length} related node(s) omitted to stay within the token budget: ${omitted.join(', ')}_\n`);
  }

  return {
    start: id, found: true,
    markdown: parts.join('\n'),
    included, omitted,
    approxTokens: Math.ceil(chars / CHARS_PER_TOKEN),
  };
}

const KIND_ORDER = ['OBJ', 'GOAL', 'KPI', 'NEED', 'FEAT', 'US', 'TASK', 'DEC', 'ASSUM', 'QUES', 'RISK'];

function renderNode(n: Node, graph: Graph): string {
  const lines: string[] = [];
  lines.push(`## ${n.id} — ${n.title}`);
  lines.push('');
  lines.push(`- kind: ${n.kind} · status: ${n.status} · epistemic: ${n.epistemic}${n.confidence ? ` (${n.confidence})` : ''}`);
  if (n.evidence) lines.push(`- evidence: ${oneLine(n.evidence)}`);
  const links = Object.entries(n.links).filter(([, v]) => v && v.length);
  if (links.length) lines.push(`- links: ${links.map(([e, v]) => `${e} → ${(v as string[]).join(', ')}`).join(' · ')}`);
  const ac = n.extra['acceptance_criteria'];
  if (Array.isArray(ac) && ac.length) {
    lines.push('- acceptance criteria:');
    for (const c of ac) lines.push(`  - ${String(c)}`);
  }
  for (const f of ['definition', 'target', 'baseline', 'instrumentation', 'who', 'context', 'rationale']) {
    const v = n.extra[f];
    if (v !== undefined && v !== null && String(v).trim() !== '') lines.push(`- ${f}: ${oneLine(String(v))}`);
  }
  const body = n.body.trim();
  if (body) { lines.push(''); lines.push(body); }
  lines.push('');
  void graph;
  return lines.join('\n');
}

function oneLine(s: string): string {
  return s.replace(/\s*\n\s*/g, ' ').trim();
}
